### ISSUE TITLE
documentation or paper

### ISSUE THREAD

**Issue by arademaker** [ibeltagy/pl-semantics#1]
Cool project, thank you for sharing. Do you have any documentation or paper describing this project? How do you compare this project with Grail 3 from Richard Moot [1]

[1] http://www.labri.fr/perso/moot/grail3.html

**Comment by ibeltagy** [comment]
For the entailment task, please read our recent CL paper https://arxiv.org/abs/1505.06816
For textual similarity using PSL, read our 2014 ACL paper https://www.cs.utexas.edu/~ml/papers/beltagy.acl14.pdf
